version: '3.9'

services:
  geos:
    build:
      context: .
    image: geos
    container_name: geos
    ports:
      - 0.0.0.0:8505:8505
      - 0.0.0.0:8506:${GRPC_SERVICE_PORT}
    environment:
      - LOG_LEVEL=debug
      - GEOIP_DB_PATH=/var/db.mmdb
      - GEOIP_DUMP_DIR=/tmp/geos/
      - GRPC_SERVICE_PORT=${GRPC_SERVICE_PORT} # 0 - disable gRPC
    volumes:
      - ${LOCAL_GEOIP_DB_PATH}:/var/db.mmdb
      - ${LOCAL_GEOIP_DUMP_PATH}:/tmp/geos/
    restart: always
